### PR TITLE
Add staff page

### PR DESCRIPTION
**Pull request by Indicardo**
Fixes issue #56

### CODE REVIEW

**Comment by jellz** [comment]
Thanks for the PR, I'll check it out this afternoon or tomorrow.

**Comment by jellz** [comment]
Did you test this PR? If so, what version of React did you use to test it? The version in the `package.json` file doesn't support React Hooks yet.

**Comment by Indicardo** [comment]
100% tested, using React 16.8, which was installed using `npm install` instead of yarn. Upgrading shouldn't be a problem

**Comment by jellz** [comment]
Thanks for contributing! :heart:

**Pull request merged**
